# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E7%BD%91%E7%AB%99
title: 'å¤œèˆ‡èŠ±æµ·'
subtitle: 'æˆ‘å¯«ä¸‹çš„â€”â€”æ˜¯ä¸–ç•Œ'
description: 'é’æ˜¥å€šé ç€æ™‚å…‰ï¼Œè¼•å¿«çš„æ­¥ä¼åœ¨ä¸–é–“æµéŸ»ï¼› é›²ä¸Šå…‰è¯å¾æŒ‡é–“ç¶»æ”¾ï¼Œåœ°ä¸Šäººå€‘è‡ªç”±è€Œå¹¸ç¦ã€‚'
keywords: hexo,blog,Suite,SuiteLHY,å¤œèˆ‡èŠ±æµ·
author: Suite
language: zh
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E7%BD%91%E5%9D%80
url: https://suitelhy.github.io/
permalink: :lang/:layout/:title/
permalink_defaults:
  lang: zh
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E7%9B%AE%E5%BD%95
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: # ç¦ç”¨ post/template éåº¦å¹²æ¶‰ raw HTML çš„è¡Œç‚º
  - _posts/README.md # Gitå­æ¨¡å— â†’ åšæ–‡ç®¡ç† â†’ é¡¹ç›®è¯´æ˜æ–‡ä»¶
  - _partial/*.html # å±€éƒ¨æ¨¡æ¿æ–‡ä»¶å¤¹ä¸‹çš„HTMLæ–‡ä»¶
  - '**/*.js'
  - '**/*.m3u8'
  - '**/*.ts'
  - '**/*.mp4'
  - '**/*.json'
  - '**/*.html'  # å¦‚æœä½ åœ¨ source ä¸­æ‰‹å‹•å¯«äº† HTML ç‰‡æ®µï¼Œä¹Ÿå»ºè­°åŠ å…¥

# Writing
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%96%87%E7%AB%A0
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: true
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
#
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
## Docs: https://github.com/hexojs/hexo-generator-index#options
#
# yearly: Generate yearly archive.
# monthly: Generate monthly archive.
# daily: Generate daily archive.
## Docs: https://www.npmjs.com/package/hexo-generator-archive#options
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E5%88%86%E7%B1%BB-amp-%E6%A0%87%E7%AD%BE
## Reference: https://ijiaober.github.io/2014/08/05/hexo/hexo-04/
## Reference: https://www.cnblogs.com/holbrook/archive/2012/11/05/2755268.html
## Reference: https://zhuanlan.zhihu.com/p/77481557
default_category: uncategorized
category_map:
  HelloWorldğŸ£: HelloWorld
  åšå®¢: Blog
  è¨ˆç®—æ©Ÿå·¥ç¨‹: ComputerEngineering
  è¨ˆç®—æ©Ÿç§‘å­¸: ComputerScience
  å…¶ä»–ğŸ—’: Other
  æ—¥å¸¸è¨˜éŒ²: DailyRecord
  æ‰‹å†Š: Handbook
  ç¤¾æœƒ: Society
  ç”Ÿå‘½: Life
  ä¿¡æ¯æŠ€è¡“: InformationTechnology
  ç«™é»è¨˜éŒ²: SiteRecord
  çŸ¥è­˜: Knowledge
tag_map:
  2022å¹´ä¸Šæµ·å°åŸ: 2022_lockdown_in_Shanghai
  Apache_Tomcat: Apache_Tomcat
  Apache_ZooKeeper: Apache_ZooKeeper
  API: API
  bcrypt: bcrypt
  Bilibili: Bilibili
  Cron: Cron
  Docker: Docker
  Elasticsearch: Elasticsearch
  Go: Go_(programming_language)
  Google: Google
  Google_Chrome: Google_Chrome
  Google_Chromeæ“´å±•ç¨‹åº: Google_Chrome_extensions
  HelloWorldğŸ£: HelloWorld
  Hibernate: Hibernate
  HTML: HTML
  HTML5: HTML5
  IDE: IDE
  IntelliJ_IDEA: IntelliJ-IDEA
  iOS: iOS
  Java: Java
  Javadoc: Javadoc
  Javaè¨»è§£: Java_annotation
  JDK: Java-Development-Kit
  Markdown: Markdown
  MyBatis: MyBatis
  MySQL: MySQL
  Node.js: Node.js
  NSFW: Not_safe_for_work
  npm: npm
  PostgreSQL: PostgreSQL
  RabbitMQ: RabbitMQ
  R18: ğŸ”
  Sass: Sass_(stylesheet_language)
  Spring_Cloud: Spring-Cloud
  Spring_Framework: Spring_Framework
  Spring_MVC: Spring-MVC
  SQL: SQL
  Thinking_in_Java: Thinking_in_Java
  Tomcat: Apache-Tomcat
  Web_API: Web_API
  Wiki: wiki
  XXL-JOB: XXL-JOB
  YouTube: YouTube
  ç·¨ç¨‹èªè¨€: Programming_language
  å¹¶ç™¼è¨ˆç®—: Concurrent_computing
  åº‡è­·æ¬Š: Right_of_asylum
  æ‚²è§€å¹¶ç™¼æ§åˆ¶: Pessimistic_Concurrency_Control
  æ‚²è§€é–: Pessimistic_Concurrency_Control
  æ¯”è¼ƒä¸¦äº¤æ›: Compare-and-swap
  åšå®¢: Blog
  è¡¨æƒ…ç¬¦è™Ÿ: Emoji
  è²å¡çˆ¾æ›²ç¶«: BÃ©zier_curve
  æ¨™æº–é€šç”¨æ¨™è¨˜èªè¨€: SGML
  åˆç­‰ä»£æ•¸: Elementary_algebra
  å±¤ç–Šæ¨£å¼è¡¨: Cascading_Style_Sheets
  é™¤æ³•: Division_(mathematics)
  åŸå¸‚: City
  æœé®®èª: Korean_language
  ç¨‹åºå“¡: Programmer
  æ“ä½œç³»çµ±: Operating_system
  é“å¾·: Moral
  å–®é»ç™»éŒ²ï¼ˆSSOï¼‰: Single_sign-on
  ä½ä»£ç¢¼é–‹ç™¼å¹³è‡º: Low-code_development_platform
  å¤§é³³: å¤§é³³(TaihÅ)
  æ±æ–¹Project: Touhou_Project
  å¾·åœ‹: Germany
  å¾·èª: German_language
  é€—è™Ÿåˆ†éš”å€¼: Comma-separated_values
  å¤§éŸ“æ°‘åœ‹: Republic_of_Korea
  åœ°å€: Region
  ä»£æ•¸: Algebra
  åœ°ä¸‹åŸèˆ‡å‹‡å£«: Dungeon_Fighter_Online
  å°è±¡é—œä¿‚æ˜ å°„: Object_Relational_Mapping
  åå…±: Anti-communism
  äºŒæ¬¡å…ƒ: ACG_(subculture)
  éæ³•ç§»æ°‘: Illegal_immigration
  æ³•åœ‹: France
  ç¬¦è™Ÿ: Symbol
  æ³•å¾‹: Law
  æœè£: Clothing
  å»£å‘Š: Advertising
  åœ‹å®¶: Country
  åœ‹éš›æ¨™æº–åŒ–çµ„ç¹”: International_Organization_for_Standardization
  åŠŸèƒ½éœ€æ±‚: Functional_requirement
  å…¬å¸: Company
  ã€Œæ€ªç‰©çµäººï¼šä¸–ç•Œã€: ã€ŒMonster_Hunter:_Worldã€
  åƒ±å‚­: Employment
  æ•…éšœå®¹è¨±åº¦: Fault_tolerance
  æ ¸å®‰å…¨: Nuclear_safety_and_security
  æ ¸é›»å» : Nuclear_power_plant
  äº’è¯ç¶²: Internet
  äº’è¯ç¶²æª”æ¡ˆé¤¨: Internet_Archive
  é»‘åå–®: Blacklisting
  é»‘åå–®ï¼ˆè¨ˆç®—ï¼‰: Blacklist_(computing)
  é»ƒæ˜å¿—: Namewee
  é»‘å®¢: Hacker
  è…³æœ¬èªè¨€: Scripting_language
  æ‹’çµ¶æœå‹™æ”»æ“Š: Denial-of-service_attack
  è¨ˆç®—æ©Ÿå·¥ç¨‹: Computer_Engineering
  è¨ˆç®—æ©Ÿç§‘å­¸: Computer_Science
  è¨ˆç®—æ©Ÿèªè¨€: Computer_language
  æµç¨‹åœ–: Flowchart
  æ¨‚è§€å¹¶ç™¼æ§åˆ¶: Optimistic_Concurrency_Control
  å€«ç†å­¸: Ethics
  ç€è¦½å™¨-æœå‹™å™¨: Browser/Server
  ç†è«–æ‰‹å†Š: Theory_Handbook
  æ­·å²: History
  è‰¯çŸ¥: Conscience
  æ—…éŠ: Tourism
  æ—…éŠè¡Œç¨‹: Travel_itinerary
  ç¶“æ¿Ÿ: Economy
  ç¶“æ¿Ÿå­¸: Economics
  ç¾åœ‹: United_States_of_America
  æ¼«ç•«: Comics
  å¯†ç¢¼æ•£åˆ—å‡½æ•¸: Cryptographic_hash_function
  é¢è©¦: Interview
  å…§æ ¸ï¼ˆæ“ä½œç³»çµ±ï¼‰: Kernel_(operating_system)
  é›£æ°‘: Refugee
  ç”·æ€§æœè£: Men's_clothing
  å¥³æ€§æœè£: Women's_clothing
  æ­æ´²è¯ç›Ÿ: European_Union
  å…¨çƒåŒ–: Globalization
  äºº: Human
  äººå·¥æ™ºèƒ½: Artificial_intelligence
  äººæ¬Š: Human_rights
  æ—¥å¸¸è¨˜éŒ²: Daily_Record
  å®¹éŒ¯æ€§: Fault_tolerance
  è»Ÿä»¶: Software
  è»Ÿä»¶å·¥ç¨‹å¸«: Software_Engineer
  è»Ÿä»¶æ¶æ§‹: Software_architecture
  è»Ÿä»¶æ¡†æ¶: Software_framework
  è»Ÿä»¶è¨­è¨ˆ: Software_design
  è»Ÿä»¶è¨­è¨ˆæ¨¡å¼: Software_design_pattern
  æ—¥æœ¬: Japan
  æ—¥èª: Japanese_language
  äººè³ªå¤–äº¤: Hostage_diplomacy
  æ›¸: Book
  æ‰‹å†Š: Handbook
  ç®—æ³•: Algorithm
  ç®—æ³•æ•ˆç‡: Algorithmic_efficiency
  ç”³æ ¹å€: Schengen_Area
  ç”³æ ¹ç°½è­‰: Visa_policy_of_the_Schengen_Area
  æ™‚é–“: Time
  æ•¸æ“šçµæ§‹: Data_structure
  æ•¸æ“šæ¨¡å‹: Data_model
  æ•¸æ“šåº«: Database
  å¯¦è¸æ‰‹å†Š: Practice_Manual
  è¨­è¨ˆæ¨¡å¼ï¼ˆå¯è¤‡ç”¨é¢å‘å°è±¡è»Ÿä»¶çš„åŸºç¤ï¼‰: Design_Patterns_(Elements_of_Reusable_Object-Oriented_Software)
  ç¤¾äº¤ç¶²çµ¡æœå‹™: Social_networking_service
  æ•¸æ“šæ˜ å°„å™¨æ¨¡å¼: Data_mapper_pattern
  æ•¸æ“šå­—å…¸: Data_dictionary
  æ·±ç©ºä¹‹çœ¼: Aether_Gazer
  è¦–é »åˆ†äº«ç¶²ç«™: Online_video_platform
  æ·±åƒæŠ€è¡“: Deepfake
  æ•¸å­¸: Math
  ä¸Šæµ·: ShangHai
  ä¸Šæµ·ç¨ç«‹é‹å‹•: Shanghai_independence_movement
  ç¤¾æœƒ: Society
  ç”Ÿå‘½: Life
  ä½¿ç”¨æ‰‹å†Š: Tutorial
  åœ–æ›¸: Book
  è‡ºç£: Taiwan
  é¨°è¨Š: Tencent
  åœ–åƒè™•ç†: Digital_Image_Processing
  å›¾åƒåˆ†æ: Image_analysis
  åœ–å½¢æ–‡ä»¶æ ¼å¼: Image_file_format
  çµ±ä¸€ç¢¼: Unicode
  é€šç”¨å”¯ä¸€è­˜åˆ¥ç¢¼: Universally_unique_identifier
  çµ±ä¸€è³‡æºæ¨™èªŒç¬¦: Uniform_Resource_Identifier
  çµ±ä¸€è³‡æºå®šä½ç¬¦: Uniform_Resource_Locator
  å°‹æ±‚åº‡è­·è€…: Asylum_seeker
  å¤–åŒ…: Outsourcing
  ç¶²é—œ: Gateway_(telecommunications)
  æ–‡æª”å°è±¡æ¨¡å‹: Document_Object_Model
  ç„¡ä»£ç¢¼é–‹ç™¼å¹³è‡º: No-code_development_platform
  æ–‡åŒ–: Culture
  ç¶²çµ¡ç¤¾å€: Online_Community
  æ­¦æ¼¢ç—…æ¯’: COVID-19
  ç¶²çµ¡ç‡ŸéŠ·: Digital_marketing
  å¤–ä¾†ç§»æ°‘: Immigration
  æ–‡æ˜: Civilization
  ç¶­åŸºç™¾ç§‘: Wikipedia
  æ–‡ä»¶å‚³è¼¸å”è­°: File_Transfer_Protocol
  æ–‡ä»¶æ•¸æ“šè½‰æ›: Data_conversion
  ç¶²ç«™æ™‚å…‰æ©Ÿ: Wayback_Machine
  é¦™æ¸¯: Hong_Kong
  æ–°åŠ å¡: Singapore
  å¿ƒç†å­¸: Psychology
  æ€§èƒ½åˆ†æ: Profiling_(computer_programming)
  è™›æ“¬YouTuber: VTuber
  è™›æ“¬ä¸»æ’­: VTuber
  è™›æ“¬æ­Œæ‰‹: Virtual_singer
  è™›æ“¬å¶åƒ: Virtual_band
  ç³»çµ±é—œä¿‚åœ–: System_context_diagram
  ç³»çµ±å¹³è‡º: Computing_platform
  å°èªª: Novel
  ä¿¡æ¯å®‰å…¨: Information_security
  æ¶ˆæ¯ä»£ç†: Message_broker
  ä¿¡æ¯æŠ€è¡“: Information_Technology
  ä¿¡æ¯ç³»çµ±: Information_system
  éŠ€è¡Œ: Bank
  ç”¨æˆ¶ç•Œé¢è¨­è¨ˆ: User_interface_design
  è—è¡“: Art
  ä»¥è‰²åˆ—: Israel
  è—è¡“å®¶: Artist
  éŠæˆ²: Game
  æ¥­å‹™æµç¨‹: Business_process
  éŠæˆ²ç‹: Yu-Gi-Oh!
  éŸ³æ¨‚: Music
  æ‡‰ç”¨ç¨‹åºæ¥å£: API
  ç«™é»è¨˜éŒ²: Site_Record
  ä¸­è¯æ°‘åœ‹: Republic_of_China
  å®—æ•™: Religion
  è¶™å®¶äºº: Zhao_family_(Internet_slang)
  çŸ¥è­˜: Knowledge
  è¨»é‡‹: Comment_(computer programming)
  è¨»é‡‹_(è¨ˆç®—æ©Ÿèªè¨€): Comment_(computer programming)
  åœ¨ç¶«å·¥å…·é¡ç¶²ç«™: Online_tool_website
  è·æ¥­: Career
  è·æ¥­ç”Ÿæ¶¯è¦åŠƒ: Career_planning
  è·æ¥­ç”Ÿæ¶¯ç®¡ç†: Career_management
  è½‰ç¾©å­—ç¬¦: Escape_character
  æ”¿æ²»: Politics
  æœ€çµ‚å¹»æƒ³XIV: Final_Fantasy_XIV

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%89%A9%E5%B1%95
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%97%A5%E6%9C%9F-%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E5%88%86%E9%A1%B5
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E5%8C%85%E6%8B%AC%E6%88%96%E4%B8%8D%E5%8C%85%E6%8B%AC%E7%9B%AE%E5%BD%95%E5%92%8C%E6%96%87%E4%BB%B6
include:
  - _partial/*.html # å±€éƒ¨æ¨¡æ¿æ–‡ä»¶å¤¹ä¸‹çš„HTMLæ–‡ä»¶
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%89%A9%E5%B1%95
theme: Kratos-Rebirth

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%89%A9%E5%B1%95
deploy:
  type: git
  repository: https://github.com/SuiteLHY/SuiteLHY.github.io
  branch: gh-pages
  message: ã€hexo-deployer-gitã€‘ã€one-command-deploymentã€‘Site updated on {{ now('YYYY-MM-DD HH:mm:ss') }}.

# hexo-renderer-markdown-it
markdown:
  render:
    html: true       # å…è¨± HTMLï¼ˆéå¸¸é‡è¦ï¼‰
    breaks: false
    linkify: true
  plugins:
    - markdown-it-container
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
