# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E7%BD%91%E7%AB%99
title: 'å¤œä¸èŠ±æµ·'
subtitle: 'æˆ‘å†™ä¸‹çš„â€”â€”æ˜¯ä¸–ç•Œ'
description: 'é’æ˜¥å€šé ç€æ—¶å…‰ï¼Œè½»å¿«çš„è„šæ­¥åœ¨ä¸–é—´æµéŸµï¼› äº‘ä¸Šå…‰åä»æŒ‡é—´ç»½æ”¾ï¼Œåœ°ä¸Šäººä»¬è‡ªç”±è€Œå¹¸ç¦ã€‚'
keywords:
author: Suite
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E7%BD%91%E5%9D%80
url: https://suitelhy.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E7%9B%AE%E5%BD%95
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - _posts/README.md # Gitå­æ¨¡å— â†’ åšæ–‡ç®¡ç† â†’ é¡¹ç›®è¯´æ˜æ–‡ä»¶

# Writing
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%96%87%E7%AB%A0
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: true
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
## Docs: https://github.com/hexojs/hexo-generator-index#options
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E5%88%86%E7%B1%BB-amp-%E6%A0%87%E7%AD%BE
## Reference: https://ijiaober.github.io/2014/08/05/hexo/hexo-04/
## Reference: https://www.cnblogs.com/holbrook/archive/2012/11/05/2755268.html
## Reference: https://zhuanlan.zhihu.com/p/77481557
default_category: uncategorized
category_map:
  Hello World: HelloWorld
  Hello World!: HelloWorld
  Hello,World: HelloWorld
  Hello,World!: HelloWorld
  Hello, World: HelloWorld
  Hello, World!: HelloWorld
  HelloWorldğŸ£: HelloWorld
  Hello WorldğŸ£: HelloWorld
  Hello World!ğŸ£: HelloWorld
  Hello,WorldğŸ£: HelloWorld
  Hello,World!ğŸ£: HelloWorld
  Hello, WorldğŸ£: HelloWorld
  Hello, World!ğŸ£: HelloWorld
  IT: InformationTechnology
  åšå®¢: Blog
  è®¡ç®—æœºå·¥ç¨‹: ComputerEngineering
  è®¡ç®—æœºç§‘å­¦: ComputerScience
  å…¶ä»–: Other
  å…¶ä»–ğŸ—’: Other
  å…¶ä»–(æš‚æœªåˆ†ç±»): Other
  æ—¥å¸¸è®°å½•: DailyRecord
  æ‰‹å†Œ: Handbook
  ç¤¾ä¼š: Society
  ç”Ÿå‘½: Life
  ä¿¡æ¯æŠ€æœ¯(IT): InformationTechnology
  ä¿¡æ¯æŠ€æœ¯: InformationTechnology
  ç«™ç‚¹è®°å½•: SiteRecord
  çŸ¥è¯†: Knowledge
tag_map:
  HelloWorldğŸ£: HelloWorld
  IT: InformationTechnology
  åšå®¢: Blog
  é“å¾·: Moral
  é“å¾·å­¦: Ethics
  é“å¾·å“²å­¦: Ethics
  åœ°åŒº: Region
  æ³•å¾‹: Law
  å›½å®¶: Country
  è®¡ç®—æœºå·¥ç¨‹: ComputerEngineering
  è®¡ç®—æœºç§‘å­¦: ComputerScience
  ä¼¦ç†: Ethics
  ä¼¦ç†å­¦: Ethics
  ç†è®ºæ‰‹å†Œ: TheoryHandbook
  è‰¯å¿ƒ: Conscience
  è‰¯çŸ¥: Conscience
  ç¾å›½: United_States_of_America
  æ—¥å¸¸è®°å½•: DailyRecord
  æ‰‹å†Œ: Handbook
  å®è·µæ‰‹å†Œ: PracticeManual
  ä½¿ç”¨æ‰‹å†Œ: Tutorial
  ç¤¾ä¼š: Society
  ç”Ÿå‘½: Life
  æ–‡åŒ–: Culture
  å¿ƒç†å­¦: Psychology
  ä¿¡æ¯æŠ€æœ¯(IT): InformationTechnology
  ä¿¡æ¯æŠ€æœ¯: InformationTechnology
  ç«™ç‚¹è®°å½•: SiteRecord

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%89%A9%E5%B1%95
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%97%A5%E6%9C%9F-%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E5%88%86%E9%A1%B5
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E5%8C%85%E6%8B%AC%E6%88%96%E4%B8%8D%E5%8C%85%E6%8B%AC%E7%9B%AE%E5%BD%95%E5%92%8C%E6%96%87%E4%BB%B6
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%89%A9%E5%B1%95
theme: Kratos-Rebirth

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%89%A9%E5%B1%95
deploy:
  type: git
  repository: https://github.com/SuiteLHY/SuiteLHY.github.io
  branch: gh-pages
  message: ã€hexo-deployer-gitã€‘ã€one-command-deploymentã€‘Site updated on {{ now('YYYY-MM-DD HH:mm:ss') }}.
