# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E7%BD%91%E7%AB%99
title: 'å¤œä¸èŠ±æµ·'
subtitle: 'æˆ‘å†™ä¸‹çš„â€”â€”æ˜¯ä¸–ç•Œ'
description: 'é’æ˜¥å€šé ç€æ—¶å…‰ï¼Œè½»å¿«çš„æ­¥ä¼åœ¨ä¸–é—´æµéŸµï¼› äº‘ä¸Šå…‰åä»æŒ‡é—´ç»½æ”¾ï¼Œåœ°ä¸Šäººä»¬è‡ªç”±è€Œå¹¸ç¦ã€‚'
keywords: hexo,blog,Suite,SuiteLHY,å¤œä¸èŠ±æµ·
author: Suite
language: zh
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E7%BD%91%E5%9D%80
url: https://suitelhy.github.io/
permalink: :lang/:layout/:title/
permalink_defaults:
  lang: zh
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E7%9B%AE%E5%BD%95
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - _posts/README.md # Gitå­æ¨¡å— â†’ åšæ–‡ç®¡ç† â†’ é¡¹ç›®è¯´æ˜æ–‡ä»¶
  - _partial/*.html # å±€éƒ¨æ¨¡æ¿æ–‡ä»¶å¤¹ä¸‹çš„HTMLæ–‡ä»¶

# Writing
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%96%87%E7%AB%A0
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: true
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
#
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
## Docs: https://github.com/hexojs/hexo-generator-index#options
#
# yearly: Generate yearly archive.
# monthly: Generate monthly archive.
# daily: Generate daily archive.
## Docs: https://www.npmjs.com/package/hexo-generator-archive#options
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E5%88%86%E7%B1%BB-amp-%E6%A0%87%E7%AD%BE
## Reference: https://ijiaober.github.io/2014/08/05/hexo/hexo-04/
## Reference: https://www.cnblogs.com/holbrook/archive/2012/11/05/2755268.html
## Reference: https://zhuanlan.zhihu.com/p/77481557
default_category: uncategorized
category_map:
  Hello World: HelloWorld
  Hello World!: HelloWorld
  Hello,World: HelloWorld
  Hello,World!: HelloWorld
  Hello, World: HelloWorld
  Hello, World!: HelloWorld
  HelloWorldğŸ£: HelloWorld
  Hello WorldğŸ£: HelloWorld
  Hello World!ğŸ£: HelloWorld
  Hello,WorldğŸ£: HelloWorld
  Hello,World!ğŸ£: HelloWorld
  Hello, WorldğŸ£: HelloWorld
  Hello, World!ğŸ£: HelloWorld
  IT: InformationTechnology
  åšå®¢: Blog
  è®¡ç®—æœºå·¥ç¨‹: ComputerEngineering
  è®¡ç®—æœºç§‘å­¦: ComputerScience
  å…¶ä»–: Other
  å…¶ä»–ğŸ—’: Other
  å…¶ä»–(æš‚æœªåˆ†ç±»): Other
  æ—¥å¸¸è®°å½•: DailyRecord
  æ‰‹å†Œ: Handbook
  ç¤¾ä¼š: Society
  ç”Ÿå‘½: Life
  ä¿¡æ¯æŠ€æœ¯(IT): InformationTechnology
  ä¿¡æ¯æŠ€æœ¯: InformationTechnology
  ç«™ç‚¹è®°å½•: SiteRecord
  çŸ¥è¯†: Knowledge
tag_map:
  ACG: ACG_(subculture)
  Apache_Tomcat: Apache_Tomcat
  Apache_ZooKeeper: Apache_ZooKeeper
  API: API
  Bilibili: Bilibili
  bilibili: Bilibili
  Browser/Server: Browser/Server
  Business_process: Business_process
  B/S: Browser/Server
  CAS: Compare-and-swap
  Cron: Cron
  CSS: Cascading_Style_Sheets
  CSV: Comma-separated_values
  Docker: Docker
  DOM: Document_Object_Model
  Elasticsearch: Elasticsearch
  Emoji: Emoji
  FTP: File_Transfer_Protocol
  Go: Go_(programming_language)
  Golang: Go_(programming_language)
  Google: Google
  Google_Chrome: Google_Chrome
  Google_Chromeæ‰©å±•ç¨‹åº: Google_Chrome_extensions
  HelloWorldğŸ£: HelloWorld
  Hibernate: Hibernate
  HTML: HTML
  HTML5: HTML5
  Human_rights: äººæƒ
  LCDP: Low-code_development_platform
  IDE: IDE
  IntelliJ_IDEA: IntelliJ-IDEA
  IntelliJ-IDEA: IntelliJ-IDEA
  iOS: iOS
  ISO: International_Organization_for_Standardization
  IT: Information_Technology
  Java: Java
  Javadoc: Javadoc
  Javaæ³¨è§£: Java_annotation
  JDK: Java-Development-Kit
  Markdown: Markdown
  MyBatis: MyBatis
  MySQL: MySQL
  NCDP: No-code_development_platform
  Node.js: Node.js
  NSFW: Not_safe_for_work
  npm: npm
  ORM: Object_Relational_Mapping
  OVP: Online_video_platform
  PostgreSQL: PostgreSQL
  RabbitMQ: RabbitMQ
  Sass: Sass_(stylesheet_language)
  SCD: System_context_diagram
  SGML: SGML
  Spring_Cloud: Spring-Cloud
  Spring_Framework: Spring_Framework
  Spring_MVC: Spring-MVC
  SQL: SQL
  SSO: Single_sign-on
  Thinking_in_Java: Thinking_in_Java
  Tomcat: Apache-Tomcat
  UI: User_interface_design
  Unicode: Unicode
  URI: Uniform_Resource_Identifier
  URL: Uniform_Resource_Locator
  UUID: Universally_unique_identifier
  Web_API: Web_API
  Wiki: wiki
  wiki: wiki
  Wikipedia: Wikipedia
  XXL-JOB: XXL-JOB
  YouTube: YouTube
  ZooKeeper: Apache_ZooKeeper
  ç¼–ç¨‹è¯­è¨€: Programming_language
  å¹¶å‘è®¡ç®—: Concurrent_computing
  æ‚²è§‚å¹¶å‘æ§åˆ¶: Pessimistic_Concurrency_Control
  æ‚²è§‚é”: Pessimistic_Concurrency_Control
  æ¯”è¾ƒå¹¶äº¤æ¢: Compare-and-swap
  åšå®¢: Blog
  è¡¨æƒ…ç¬¦å·: Emoji
  è´å¡å°”æ›²çº¿: BÃ©zier_curve
  æ ‡å‡†é€šç”¨æ ‡è®°è¯­è¨€: SGML
  åˆç­‰ä»£æ•°: Elementary_algebra
  å±‚å æ ·å¼è¡¨: Cascading_Style_Sheets
  é™¤æ³•: Division_(mathematics)
  åŸå¸‚: City
  ç¨‹åºå‘˜: Programmer
  æ“ä½œç³»ç»Ÿ: Operating_system
  é“å¾·: Moral
  å•ç‚¹ç™»å½•: Single_sign-on
  å•ç‚¹ç™»å½•ï¼ˆSSOï¼‰: Single_sign-on
  ä½ä»£ç å¼€å‘å¹³å°: Low-code_development_platform
  é“å¾·å­¦: Ethics
  é“å¾·å“²å­¦: Ethics
  å¤§é³³: å¤§é³³(TaihÅ)
  å¤§å‡¤: å¤§é³³(TaihÅ)
  ä¸œæ–¹Project: Touhou_Project
  é€—å·åˆ†éš”å€¼: Comma-separated_values
  åœ°åŒº: Region
  ä»£æ•°: Algebra
  åœ°ä¸‹åŸä¸å‹‡å£«: Dungeon_Fighter_Online
  å¯¹è±¡å…³ç³»æ˜ å°„: Object_Relational_Mapping
  åå…±: Anti-communism
  äºŒæ¬¡å…ƒ: ACG_(subculture)
  æ³•å¾‹: Law
  å¹¿å‘Š: Advertising
  å›½å®¶: Country
  å›½é™…æ ‡å‡†åŒ–ç»„ç»‡: International_Organization_for_Standardization
  åŠŸèƒ½éœ€æ±‚: Functional_requirement
  å…¬å¸: Company
  é›‡ä½£: Employment
  æ•…éšœå®¹è®¸åº¦: Fault_tolerance
  æ ¸å®‰å…¨: Nuclear_safety_and_security
  æ ¸ç”µå‚: Nuclear_power_plant
  äº’è”ç½‘: Internet
  äº’è”ç½‘æ¡£æ¡ˆé¦†: Internet_Archive
  é»‘åå•: Blacklisting
  é»‘åå•ï¼ˆè®¡ç®—ï¼‰: Blacklist_(computing)
  é»„æ˜å¿—: Namewee
  é»‘å®¢: Hacker
  è„šæœ¬è¯­è¨€: Scripting_language
  æ‹’ç»æœåŠ¡æ”»å‡»: Denial-of-service_attack
  è®¡ç®—æœºå·¥ç¨‹: Computer_Engineering
  è®¡ç®—æœºç§‘å­¦: Computer_Science
  è®¡ç®—æœºè¯­è¨€: Computer_language
  æµç¨‹å›¾: Flowchart
  ä¹è§‚å¹¶å‘æ§åˆ¶: Optimistic_Concurrency_Control
  ä¹è§‚é”: Optimistic_Concurrency_Control
  ä¼¦ç†: Ethics
  ä¼¦ç†å­¦: Ethics
  æµè§ˆå™¨-æœåŠ¡å™¨: Browser/Server
  ç†è®ºæ‰‹å†Œ: Theory_Handbook
  å†å²: History
  è‰¯å¿ƒ: Conscience
  è‰¯çŸ¥: Conscience
  ç»æµ: Economy
  ç¾å›½: United_States_of_America
  æ¼«ç”»: Comics
  å¯†ç æ•£åˆ—å‡½æ•°: Cryptographic_hash_function
  é¢è¯•: Interview
  å†…æ ¸ï¼ˆæ“ä½œç³»ç»Ÿï¼‰: Kernel_(operating_system)
  å…¨çƒåŒ–: Globalization
  äºº: Human
  äººæƒ: Human_rights
  æ—¥å¸¸è®°å½•: Daily_Record
  å®¹é”™æ€§: Fault_tolerance
  è½¯ä»¶: Software
  è½¯ä»¶å·¥ç¨‹å¸ˆ: Software_Engineer
  è½¯ä»¶æ¶æ„: Software_architecture
  è½¯ä»¶æ¡†æ¶: Software_framework
  è½¯ä»¶è®¾è®¡: Software_design
  è½¯ä»¶è®¾è®¡æ¨¡å¼: Software_design_pattern
  æ—¥æœ¬: Japan
  æ—¥è¯­: Japanese_language
  ä¹¦: Book
  æ‰‹å†Œ: Handbook
  ç®—æ³•: Algorithm
  ç®—æ³•æ•ˆç‡: Algorithmic_efficiency
  æ—¶é—´: Time
  æ•°æ®ç»“æ„: Data_structure
  æ•°æ®æ¨¡å‹: Data_model
  æ•°æ®åº“: Database
  å®è·µæ‰‹å†Œ: Practice_Manual
  è®¾è®¡æ¨¡å¼ï¼ˆå¯å¤ç”¨é¢å‘å¯¹è±¡è½¯ä»¶çš„åŸºç¡€ï¼‰: Design_Patterns_(Elements_of_Reusable_Object-Oriented_Software)
  ç¤¾äº¤ç½‘ç»œæœåŠ¡: Social_networking_service
  æ•°æ®æ˜ å°„å™¨æ¨¡å¼: Data_mapper_pattern
  æ•°æ®å­—å…¸: Data_dictionary
  æ·±ç©ºä¹‹çœ¼: Aether_Gazer
  è§†é¢‘åˆ†äº«ç½‘ç«™: Online_video_platform
  æ•°å­¦: Math
  ä½¿ç”¨æ‰‹å†Œ: Tutorial
  ä¸Šæµ·: ShangHai
  ç¤¾ä¼š: Society
  ç”Ÿå‘½: Life
  å›¾ä¹¦: Book
  å›¾åƒå¤„ç†: Digital_Image_Processing
  å›¾åƒæ ¼å¼: Image_File_Format
  å›¾ç‰‡æ ¼å¼: Image_File_Format
  å›¾åƒåˆ†æ: Image_analysis
  å›¾åƒæ–‡ä»¶æ ¼å¼: Image_File_Format
  å›¾ç‰‡æ–‡ä»¶æ ¼å¼: Image_File_Format
  å›¾å½¢æ–‡ä»¶æ ¼å¼: Image_File_Format
  ç»Ÿä¸€ç : Unicode
  é€šç”¨å”¯ä¸€è¯†åˆ«ç : Universally_unique_identifier
  ç»Ÿä¸€èµ„æºæ ‡å¿—ç¬¦: Uniform_Resource_Identifier
  ç»Ÿä¸€èµ„æºå®šä½ç¬¦: Uniform_Resource_Locator
  å¤–åŒ…: Outsourcing
  ç½‘å…³: Gateway_(telecommunications)
  æ–‡æ¡£å¯¹è±¡æ¨¡å‹: Document_Object_Model
  æ— ä»£ç å¼€å‘å¹³å°: No-code_development_platform
  æ–‡åŒ–: Culture
  ç½‘ç»œç¤¾åŒº: Online_Community
  äº’è”ç½‘ç¤¾åŒº: Online_Community
  åœ¨çº¿ç¤¾åŒº: Online_Community
  æ­¦æ±‰ç—…æ¯’: COVID-19
  ç½‘ç»œè¥é”€: Digital_marketing
  ç»´åŸºç™¾ç§‘: Wikipedia
  æ–‡ä»¶ä¼ è¾“åè®®: File_Transfer_Protocol
  æ–‡ä»¶æ•°æ®è½¬æ¢: Data_conversion
  ç½‘ç«™æ—¶å…‰æœº: Wayback_Machine
  é¦™æ¸¯: Hong_Kong
  å¿ƒç†å­¦: Psychology
  æ€§èƒ½åˆ†æ: Profiling_(computer_programming)
  ç³»ç»Ÿå…³ç³»å›¾: System_context_diagram
  ç³»ç»Ÿå¹³å°: Computing_platform
  ä¿¡æ¯å®‰å…¨: Information_security
  æ¶ˆæ¯ä»£ç†: Message_broker
  ä¿¡æ¯æŠ€æœ¯(IT): Information_Technology
  ä¿¡æ¯æŠ€æœ¯: Information_Technology
  ä¿¡æ¯ç³»ç»Ÿ: Information_system
  ç”¨æˆ·ç•Œé¢è®¾è®¡: User_interface_design
  è‰ºæœ¯: Art
  è‰ºæœ¯å®¶: Artist
  æ¸¸æˆ: Game
  ä¸šåŠ¡è¿‡ç¨‹: Business_process
  ä¸šåŠ¡æµç¨‹: Business_process
  éŸ³ä¹: Music
  åº”ç”¨ç¨‹åºæ¥å£: API
  ç«™ç‚¹è®°å½•: Site_Record
  ä¸­åæ°‘å›½: Republic_of_China
  èµµå®¶äºº: è¶™å®¶äºº
  çŸ¥è¯†: Knowledge
  æ³¨é‡Š: Comment_(computer programming)
  æ³¨é‡Š_(è®¡ç®—æœºè¯­è¨€): Comment_(computer programming)
  åœ¨çº¿å·¥å…·ç±»ç½‘ç«™: Online_tool_website
  èŒä¸š: Career
  èŒä¸šç”Ÿæ¶¯è§„åˆ’: Career_planning
  èŒä¸šç”Ÿæ¶¯ç®¡ç†: Career_management
  è½¬ä¹‰å­—ç¬¦: Escape_character
  æ”¿æ²»: Politics
  ã€å¯†ç æ•£åˆ—å‡½æ•°ã€‘bcrypt: bcrypt

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%89%A9%E5%B1%95
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%97%A5%E6%9C%9F-%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E5%88%86%E9%A1%B5
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E5%8C%85%E6%8B%AC%E6%88%96%E4%B8%8D%E5%8C%85%E6%8B%AC%E7%9B%AE%E5%BD%95%E5%92%8C%E6%96%87%E4%BB%B6
include:
  - _partial/*.html # å±€éƒ¨æ¨¡æ¿æ–‡ä»¶å¤¹ä¸‹çš„HTMLæ–‡ä»¶
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%89%A9%E5%B1%95
theme: Kratos-Rebirth

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
## Docs: https://hexo.io/zh-cn/docs/configuration.html#%E6%89%A9%E5%B1%95
deploy:
  type: git
  repository: https://github.com/SuiteLHY/SuiteLHY.github.io
  branch: gh-pages
  message: ã€hexo-deployer-gitã€‘ã€one-command-deploymentã€‘Site updated on {{ now('YYYY-MM-DD HH:mm:ss') }}.
